language: java
jdk: oraclejdk8
cache:
  directories:
    - "~/.m2"
script:
  - "./mvnw -B install"
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
after_success:
  - ./cd/before-deploy.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "Deploying to Nexus..."; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ./mvnw deploy --settings ./.m2/settings.xml -DskipTests=true -B; fi
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then echo "Deploying to Nexus..."; fi
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then ./mvnw deploy --settings ./.m2/settings.xml -DskipTests=true -B; fi
dd:
  - openssl aes-256-cbc -K $encrypted_50f149f527b5_key -iv $encrypted_50f149f527b5_iv -in codesigning.asc.enc -out codesigning.asc -d
